// @generated by scripts/generate-app-server-types.mjs — do not edit by hand.
// Source: vendor/bingo/app-server-schema/v1.0 (bingo app-server v1.0, schema bundle v1).
// Unknown JSON fields are additive within protocol major 1; generated fields are
// intentionally the committed contract, not an exhaustive wire validator.

// Action
export type Action = { type: "sessionReset" } | { name: string; type: "sessionRename" } | { type: "sessionGarbageCollect" } | { open: boolean; output?: string | null; public: boolean; type: "sessionShare" } | { path: string; type: "sessionChangeDirectory" } | { instructions?: string | null; type: "conversationCompact" } | { mode: RewindMode; target: RewindTarget; type: "conversationRewind" } | { model: string; type: "modelSelect" } | { provider: string; type: "providerSelect" } | { provider: string; type: "providerLogin" } | { provider: string; type: "providerLogout" } | { level: ThinkingLevel; type: "thinkingSelect" } | { mode: PermissionMode; type: "permissionModeSet" } | { decision: PermissionRuleDecision; rule: string; type: "permissionRuleAdd" } | { decision: PermissionRuleDecision; rule: string; type: "permissionRuleRemove" } | { server: string; type: "mcpEnable" } | { server: string; type: "mcpDisable" } | { server?: string | null; type: "mcpReconnect" } | { input?: string | null; skill: string; type: "skillInvoke" } | { members?: Array<string> | null; type: "teamStart" } | { member: string; task: string; type: "teamAssign" } | { member?: string | null; type: "teamStop" } | { name: string; type: "teamScaffold" } | { type: "teamMemoryGarbageCollect" } | { room: string; type: "roomJoin" } | { room: string; type: "roomLeave" } | { itemId: ItemId; type: "commandPromote" } | { theme: ThemeChoice; type: "themeSet" }

// ActionArgument
export interface ActionArgument {
  choices: Array<string>
  description: string
  kind: ArgumentKind
  name: string
  required: boolean
}

// ActionExecuteParams
export interface ActionExecuteParams {
  action: Action
  originConversationId: ConversationId
  precondition?: ResourceRevision | null
}

// ActionExecuteResult
export interface ActionExecuteResult {
  disposition: SubmitDisposition
}

// ActionFamily
export type ActionFamily = "session" | "conversation" | "model" | "provider" | "permission" | "mcp" | "skill" | "team" | "room" | "command" | "settings"

// ActionId
export type ActionId = string

// ActionInfo
export interface ActionInfo {
  arguments: Array<ActionArgument>
  available: boolean
  description: string
  family: ActionFamily
  id: ActionId
  label: string
  preconditionScope?: RevisionScope | null
  unavailableReason?: string | null
}

// ActionListParams
export interface ActionListParams {
  originConversationId?: ConversationId | null
}

// ActionListResult
export interface ActionListResult {
  actions: Array<ActionInfo>
  revision: number
}

// ActionResult
export interface ActionResult {
  message?: string | null
  revision?: ResourceRevision | null
  status: ActionResultStatus
}

// ActionResultStatus
export type ActionResultStatus = "applied" | "noChange"

// ActivationKind
export type ActivationKind = "pointer" | "keyboard" | "programmatic"

// AgentId
export type AgentId = string

// AgentKind
export type AgentKind = "crew" | "hire"

// AgentResource
export interface AgentResource {
  conversationId?: ConversationId | null
  cwd: string
  def?: string | null
  description: string
  elapsedMs?: number | null
  id: AgentId
  kind: AgentKind
  lastActiveAt: number
  model: string
  name: string
  outputTokens: number
  pending: number
  prompt: string
  provider: string
  recentActivity: Array<string>
  state: AgentState
  thinking: ThinkingLevel
  toolUses: number
  unacked: number
}

// AgentState
export type AgentState = "running" | "idle" | "stopped"

// ArgumentKind
export type ArgumentKind = "string" | "integer" | "boolean" | "path" | "enumeration"

// AssetId
export type AssetId = string

// AssetKind
export type AssetKind = "image" | "text" | "binary"

// AssetOrigin
export type AssetOrigin = "session" | "transcript"

// AssetReadChunkParams
export interface AssetReadChunkParams {
  assetId: AssetId
  length: number
  offset: number
}

// AssetReadChunkResult
export interface AssetReadChunkResult {
  data: string
  eof: boolean
  nextOffset: number
}

// AssetRecord
export interface AssetRecord {
  bytes: number
  createdAt: number
  height?: number | null
  id: AssetId
  kind: AssetKind
  mime: string
  origin: AssetOrigin
  sha256: string
  width?: number | null
}

// AssetRegisterPathParams
export interface AssetRegisterPathParams {
  expectedMime?: string | null
  expectedSha256?: string | null
  path: string
}

// AssetRegisterPathResult
export interface AssetRegisterPathResult {
  asset: AssetRecord
}

// BackgroundCommandResource
export interface BackgroundCommandResource {
  command: string
  conversationId?: ConversationId | null
  durationMs: number
  exitCode?: number | null
  id: CommandId
  itemId?: ItemId | null
  label: string
  startedAt: number
  state: BackgroundCommandState
}

// BackgroundCommandState
export type BackgroundCommandState = "running" | "done" | "failed" | "cancelled" | "idle"

// Catalog
export type Catalog = { catalog: "models"; items: Array<ModelInfo>; nextCursor?: string | null; revision: number } | { catalog: "providers"; items: Array<ProviderInfo>; nextCursor?: string | null; revision: number } | { catalog: "skills"; items: Array<SkillInfo>; nextCursor?: string | null; revision: number } | { catalog: "mcpServers"; items: Array<McpServerState>; nextCursor?: string | null; revision: number } | { catalog: "images"; items: Array<ImageInfo>; nextCursor?: string | null; revision: number }

// CatalogKind
export type CatalogKind = "models" | "providers" | "skills" | "mcpServers" | "images"

// CatalogReadParams
export interface CatalogReadParams {
  catalog: CatalogKind
  cursor?: string | null
  limit?: number | null
  provider?: string | null
}

// CatalogReadResult
export interface CatalogReadResult {
  catalog: Catalog
}

// ClientCapabilities
export interface ClientCapabilities {
  experimental?: Array<string>
  interactionResponse: boolean
}

// ClientInfo
export interface ClientInfo {
  name: string
  version: string
}

// Collection_for_AgentResource
export interface Collection_for_AgentResource {
  active: Array<AgentResource>
  count: number
  revision: number
}

// Collection_for_BackgroundCommandResource
export interface Collection_for_BackgroundCommandResource {
  active: Array<BackgroundCommandResource>
  count: number
  revision: number
}

// Collection_for_ConversationSummary
export interface Collection_for_ConversationSummary {
  active: Array<ConversationSummary>
  count: number
  revision: number
}

// Collection_for_DeliveryResource
export interface Collection_for_DeliveryResource {
  active: Array<DeliveryResource>
  count: number
  revision: number
}

// Collection_for_RoomResource
export interface Collection_for_RoomResource {
  active: Array<RoomResource>
  count: number
  revision: number
}

// Collection_for_TaskResource
export interface Collection_for_TaskResource {
  active: Array<TaskResource>
  count: number
  revision: number
}

// CommandId
export type CommandId = string

// CommandTail
export interface CommandTail {
  lines: Array<string>
  totalLines: number
}

// ComposerMode
export type ComposerMode = "normal" | "shell"

// ConfigLayer
export interface ConfigLayer {
  keys: Array<string>
  path: string
}

// ConfigReadParams
export interface ConfigReadParams {
  sections?: Array<ConfigSection> | null
}

// ConfigReadResult
export interface ConfigReadResult {
  config: ConfigSnapshot
}

// ConfigSection
export type ConfigSection = "selection" | "permissions" | "layers" | "mcp"

// ConfigSnapshot
export interface ConfigSnapshot {
  cwd: string
  layers: Array<ConfigLayer>
  mcpServers: Array<McpServerState>
  model: string
  permissionMode: PermissionMode
  permissions: Array<PermissionRule>
  provider: string
  revision: number
  shell: string
  shellDialect: ShellDialect
  theme: ThemeChoice
  thinking: ThinkingLevel
}

// ContextUsage
export interface ContextUsage {
  trigger: number
  used: number
  window: number
}

// ConversationId
export type ConversationId = string

// ConversationKind
export type ConversationKind = { type: "main" } | { agentId: AgentId; type: "agent" } | { roomId: RoomId; type: "room" }

// ConversationListParams
export interface ConversationListParams {
  cursor?: string | null
  limit?: number | null
}

// ConversationListResult
export interface ConversationListResult {
  conversations: Page_for_ConversationSummary
}

// ConversationMarkReadParams
export interface ConversationMarkReadParams {
  conversationId: ConversationId
  expectedRevision: number
  lastItemId?: ItemId | null
  lastRoomSeq?: number | null
}

// ConversationMarkReadResult
export interface ConversationMarkReadResult {
  conversation: ConversationSummary
}

// ConversationReadParams
export interface ConversationReadParams {
  conversationId: ConversationId
  cursor?: ItemCursor | null
  limit?: number | null
}

// ConversationReadResult
export interface ConversationReadResult {
  snapshot: ConversationSnapshot
}

// ConversationRunState
export type ConversationRunState = "idle" | "running" | "stopped" | "passive"

// ConversationSnapshot
export interface ConversationSnapshot {
  activeTurn?: Turn | null
  contextUsage?: ContextUsage | null
  conversation: ConversationSummary
  eventCursor: number
  historyGeneration: number
  interactions: Array<Interaction>
  items: Page_for_Item
  queue: Page_for_QueueEntry
}

// ConversationSubmitParams
export interface ConversationSubmitParams {
  conversationId: ConversationId
  input: Submission
}

// ConversationSubmitResult
export interface ConversationSubmitResult {
  disposition: SubmitDisposition
}

// ConversationSummary
export interface ConversationSummary {
  activeTurnId?: TurnId | null
  historyGeneration: number
  id: ConversationId
  isMember: boolean
  kind: ConversationKind
  lastActivityAt?: number | null
  lastItemId?: ItemId | null
  mentions: number
  obligations: Array<Obligation>
  pendingInteractions: number
  queueCount: number
  queueRevision: number
  readCursor?: ItemId | null
  revision: number
  runState: ConversationRunState
  title: string
  unread: number
}

// CredentialSource
export type CredentialSource = "environment" | "settings" | "oauthStore" | "none"

// CredentialState
export interface CredentialState {
  configured: boolean
  source: CredentialSource
  status: CredentialStatus
}

// CredentialStatus
export type CredentialStatus = "present" | "missing" | "expired" | "unknown"

// DeliveryId
export type DeliveryId = string

// DeliveryResource
export interface DeliveryResource {
  followUps: number
  from: string
  id: DeliveryId
  maxFollowUps: number
  messageItemId?: ItemId | null
  private: boolean
  reason?: string | null
  state: DeliveryState
  to: string
  updatedAt: number
}

// DeliveryState
export type DeliveryState = "queued" | "delivered" | "read" | "answered" | "dropped"

// EpochId
export type EpochId = string

// ErrorData
export interface ErrorData {
  assetId?: AssetId | null
  bingoCode: string
  conversationId?: ConversationId | null
  interactionId?: InteractionId | null
  itemId?: ItemId | null
  operationId?: OperationId | null
  queueId?: QueueId | null
  recoverable: boolean
  scope: ErrorScope
  sessionId?: SessionId | null
  suggestedAction?: SuggestedAction | null
  turnId?: TurnId | null
}

// ErrorScope
export type ErrorScope = "connection" | "session" | "conversation" | "turn" | "item" | "queue" | "interaction" | "operation" | "asset" | "action" | "request"

// EventMeta
export interface EventMeta {
  causedBy?: OperationId | null
  coalescedFrom?: number | null
  seq: number
  sessionId: SessionId
  ts: number
}

// Feedback
export interface Feedback {
  code: string
  conversationId?: ConversationId | null
  detail?: string | null
  expiresAt?: number | null
  id: FeedbackId
  level: NoticeLevel
  message: string
  raisedAt: number
}

// FeedbackId
export type FeedbackId = string

// FrameLimits
export interface FrameLimits {
  maxClientFrameBytes: number
  maxServerFrameBytes: number
}

// ImageInfo
export interface ImageInfo {
  assetId: AssetId
  bytes: number
  createdAt: number
  height: number
  label?: string | null
  width: number
}

// InitializeParams
export interface InitializeParams {
  capabilities: ClientCapabilities
  client: ClientInfo
  protocol: ProtocolRange
}

// InitializeResult
export interface InitializeResult {
  capabilities: ServerCapabilities
  limits: FrameLimits
  protocol: ProtocolVersion
  server: ServerInfo
}

// InitializedParams
export type InitializedParams = Record<string, unknown>

// Interaction
export interface Interaction {
  conversationId: ConversationId
  id: InteractionId
  itemId?: ItemId | null
  openedAt: number
  prompt: InteractionPrompt
  remainingGuardMs: number
  turnId?: TurnId | null
}

// InteractionCancelReason
export type InteractionCancelReason = "interrupted" | "sessionClosed" | "turnEnded"

// InteractionDecision
export type InteractionDecision = { type: "allowOnce" } | { scopeId: ScopeId; type: "allowSession" } | { feedback?: string | null; type: "deny" } | { optionId?: string | null; text?: string | null; type: "answer" } | { type: "confirm" } | { type: "cancel" }

// InteractionId
export type InteractionId = string

// InteractionPreview
export type InteractionPreview = { command: string; type: "command" } | { diff: string; type: "diff" }

// InteractionPrompt
export type InteractionPrompt = { allowsFeedback: boolean; decisions: Array<PermissionDecisionKind>; preview?: InteractionPreview | null; reason?: string | null; sessionScope?: SessionScope | null; title: string; tool: ToolRequest; type: "permission" } | { allowsFreeText: boolean; options: Array<QuestionOption>; question: string; title: string; type: "question" } | { confirmLabel: string; detail: string; title: string; type: "confirmation" }

// InteractionRespondParams
export interface InteractionRespondParams {
  activation: ActivationKind
  decision: InteractionDecision
  interactionId: InteractionId
}

// InteractionRespondResult
export interface InteractionRespondResult {
  itemId?: ItemId | null
  status: RespondStatus
}

// Item
export type Item = { completedAt?: number | null; id: ItemId; startedAt?: number | null; status: ItemStatus; turnId?: TurnId | null } & ({ attachments: Array<AssetId>; text: string; type: "userMessage" } | { text: string; type: "assistantMessage" } | { deliveryId?: DeliveryId | null; from: string; text: string; to?: string | null; type: "peerMessage" } | { from: string; mentions: Array<string>; roomId: RoomId; roomSeq: number; text: string; type: "roomMessage" } | { text: string; type: "reasoning" } | { artifact?: AssetId | null; diff?: string | null; durationMs: number; input: unknown; name: string; output: string; summary: string; toolCallId: string; type: "toolCall" } | { artifact?: AssetId | null; background: boolean; command: string; commandId?: CommandId | null; dialect: ShellDialect; durationMs: number; exitCode?: number | null; output: string; tail?: CommandTail | null; type: "command" } | { afterTokens: number; beforeTokens: number; durationMs: number; replacedMessages: number; type: "compaction" } | { mode: RewindMode; removedItems: number; targetItemId?: ItemId | null; type: "rewind" } | { marker: string; type: "interruption" } | { code: string; level: NoticeLevel; text: string; type: "notice" } | { answer: string; interactionId: InteractionId; optionId?: string | null; question: string; type: "questionAnswer" } | { decision: PermissionDecisionKind; feedback?: string | null; interactionId: InteractionId; scopeId?: ScopeId | null; tool: string; type: "permissionReceipt" } | { assetId: AssetId; label?: string | null; type: "asset" })

// ItemCursor
export interface ItemCursor {
  after: ItemId
  historyGeneration: number
}

// ItemId
export type ItemId = string

// ItemStatus
export type ItemStatus = "pending" | "streaming" | "completed" | "failed" | "cancelled"

// JsonRpcVersion
export type JsonRpcVersion = "2.0"

// McpServerState
export interface McpServerState {
  enabled: boolean
  error?: string | null
  name: string
  status: McpStatus
  tools: number
}

// McpStatus
export type McpStatus = "connecting" | "connected" | "disconnected" | "error"

// ModelInfo
export interface ModelInfo {
  contextWindow?: number | null
  displayName?: string | null
  family?: string | null
  id: string
  provider: string
  supportsImages: boolean
  supportsThinking: boolean
}

// NoticeLevel
export type NoticeLevel = "info" | "warning" | "error"

// NotificationParams_for_AgentChanged
export interface NotificationParams_for_AgentChanged {
  agent: AgentResource
  event: EventMeta
}

// NotificationParams_for_AgentRemoved
export interface NotificationParams_for_AgentRemoved {
  agentId: AgentId
  event: EventMeta
}

// NotificationParams_for_AssetAvailable
export interface NotificationParams_for_AssetAvailable {
  asset: AssetRecord
  event: EventMeta
}

// NotificationParams_for_CatalogChanged
export interface NotificationParams_for_CatalogChanged {
  catalog: CatalogKind
  event: EventMeta
  revision: number
}

// NotificationParams_for_CommandChanged
export interface NotificationParams_for_CommandChanged {
  command: BackgroundCommandResource
  event: EventMeta
}

// NotificationParams_for_ConfigChanged
export interface NotificationParams_for_ConfigChanged {
  config: ConfigSnapshot
  event: EventMeta
}

// NotificationParams_for_ConversationChanged
export interface NotificationParams_for_ConversationChanged {
  conversation: ConversationSummary
  event: EventMeta
}

// NotificationParams_for_ConversationRemoved
export interface NotificationParams_for_ConversationRemoved {
  conversationId: ConversationId
  event: EventMeta
}

// NotificationParams_for_DeliveryChanged
export interface NotificationParams_for_DeliveryChanged {
  delivery: DeliveryResource
  event: EventMeta
}

// NotificationParams_for_FeedbackCleared
export interface NotificationParams_for_FeedbackCleared {
  event: EventMeta
  feedbackId: FeedbackId
}

// NotificationParams_for_FeedbackRaised
export interface NotificationParams_for_FeedbackRaised {
  event: EventMeta
  feedback: Feedback
}

// NotificationParams_for_InteractionCancelled
export interface NotificationParams_for_InteractionCancelled {
  conversationId: ConversationId
  event: EventMeta
  interactionId: InteractionId
  reason: InteractionCancelReason
}

// NotificationParams_for_InteractionOpened
export interface NotificationParams_for_InteractionOpened {
  event: EventMeta
  interaction: Interaction
}

// NotificationParams_for_InteractionResolved
export interface NotificationParams_for_InteractionResolved {
  conversationId: ConversationId
  decision: InteractionDecision
  event: EventMeta
  interactionId: InteractionId
  itemId?: ItemId | null
}

// NotificationParams_for_ItemChanged
export interface NotificationParams_for_ItemChanged {
  conversationId: ConversationId
  event: EventMeta
  item: Item
  turnId?: TurnId | null
}

// NotificationParams_for_ItemCommandTailUpdated
export interface NotificationParams_for_ItemCommandTailUpdated {
  conversationId: ConversationId
  event: EventMeta
  itemId: ItemId
  tail: CommandTail
  turnId?: TurnId | null
}

// NotificationParams_for_ItemDelta
export interface NotificationParams_for_ItemDelta {
  conversationId: ConversationId
  delta: string
  deltaSeq: number
  event: EventMeta
  itemId: ItemId
  turnId?: TurnId | null
}

// NotificationParams_for_OperationChanged
export interface NotificationParams_for_OperationChanged {
  event: EventMeta
  operation: Operation
}

// NotificationParams_for_OperationProgressed
export interface NotificationParams_for_OperationProgressed {
  event: EventMeta
  operationId: OperationId
  progress: OperationProgress
}

// NotificationParams_for_QueueItemAbsorbed
export interface NotificationParams_for_QueueItemAbsorbed {
  conversationId: ConversationId
  event: EventMeta
  itemId: ItemId
  queueId: QueueId
  revision: number
  turnId: TurnId
}

// NotificationParams_for_QueueItemAdded
export interface NotificationParams_for_QueueItemAdded {
  conversationId: ConversationId
  entry: QueueEntry
  event: EventMeta
  position: number
  revision: number
}

// NotificationParams_for_QueueItemRemoved
export interface NotificationParams_for_QueueItemRemoved {
  conversationId: ConversationId
  event: EventMeta
  queueId: QueueId
  reason: QueueRemovalReason
  revision: number
}

// NotificationParams_for_RoomChanged
export interface NotificationParams_for_RoomChanged {
  event: EventMeta
  room: RoomResource
}

// NotificationParams_for_SessionClosed
export interface NotificationParams_for_SessionClosed {
  event: EventMeta
  reason: SessionCloseReason
  sessionId: SessionId
}

// NotificationParams_for_SessionDeleted
export interface NotificationParams_for_SessionDeleted {
  event: EventMeta
  locator: SessionLocator
}

// NotificationParams_for_SessionUpdated
export interface NotificationParams_for_SessionUpdated {
  event: EventMeta
  session: SessionSummary
}

// NotificationParams_for_TaskChanged
export interface NotificationParams_for_TaskChanged {
  event: EventMeta
  task: TaskResource
}

// NotificationParams_for_TaskRemoved
export interface NotificationParams_for_TaskRemoved {
  event: EventMeta
  taskId: TaskId
}

// NotificationParams_for_TurnChanged
export interface NotificationParams_for_TurnChanged {
  conversationId: ConversationId
  event: EventMeta
  turn: Turn
}

// NotificationParams_for_TurnRetrying
export interface NotificationParams_for_TurnRetrying {
  attempt: number
  code?: string | null
  conversationId: ConversationId
  delayMs: number
  event: EventMeta
  maxAttempts: number
  reason?: string | null
  removedItemIds: Array<ItemId>
  round: number
  turnId: TurnId
}

// NotificationParams_for_TurnRoundCompleted
export interface NotificationParams_for_TurnRoundCompleted {
  conversationId: ConversationId
  event: EventMeta
  round: number
  turnId: TurnId
  usage?: TurnUsage | null
}

// NotificationParams_for_TurnRoundStarted
export interface NotificationParams_for_TurnRoundStarted {
  conversationId: ConversationId
  event: EventMeta
  round: number
  turnId: TurnId
}

// NotificationParams_for_TurnUsageUpdated
export interface NotificationParams_for_TurnUsageUpdated {
  contextUsage?: ContextUsage | null
  conversationId: ConversationId
  event: EventMeta
  turnId: TurnId
  usage: TurnUsage
}

// Obligation
export interface Obligation {
  from?: string | null
  itemId?: ItemId | null
  kind: ObligationKind
  since: number
}

// ObligationKind
export type ObligationKind = "mentionDebt" | "awaitingUser" | "unansweredMessage"

// Operation
export interface Operation {
  completedAt?: number | null
  conversationId?: ConversationId | null
  error?: TurnError | null
  id: OperationId
  kind: OperationKind
  progress?: OperationProgress | null
  startedAt: number
  status: OperationStatus
}

// OperationId
export type OperationId = string

// OperationKind
export type OperationKind = "providerLogin" | "providerLogout" | "share" | "mcpReconnect" | "teamStart" | "garbageCollect" | "compact" | "rewind" | "sessionDelete" | "skillInvoke"

// OperationProgress
export interface OperationProgress {
  done?: number | null
  label: string
  total?: number | null
}

// OperationStatus
export type OperationStatus = "running" | "completed" | "failed" | "cancelled"

// Page_for_ConversationSummary
export interface Page_for_ConversationSummary {
  items: Array<ConversationSummary>
  nextCursor?: string | null
  revision: number
}

// Page_for_Item
export interface Page_for_Item {
  items: Array<Item>
  nextCursor?: string | null
  revision: number
}

// Page_for_QueueEntry
export interface Page_for_QueueEntry {
  items: Array<QueueEntry>
  nextCursor?: string | null
  revision: number
}

// Page_for_SessionListEntry
export interface Page_for_SessionListEntry {
  items: Array<SessionListEntry>
  nextCursor?: string | null
  revision: number
}

// PermissionDecisionKind
export type PermissionDecisionKind = "allowOnce" | "allowSession" | "deny"

// PermissionMode
export type PermissionMode = "default" | "acceptEdits" | "bypassPermissions" | "dontAsk" | "plan"

// PermissionRule
export interface PermissionRule {
  decision: PermissionRuleDecision
  rule: string
  sessionScoped: boolean
}

// PermissionRuleDecision
export type PermissionRuleDecision = "allow" | "deny" | "ask"

// ProtocolRange
export interface ProtocolRange {
  major: number
  maxMinor: number
  minMinor: number
}

// ProtocolVersion
export interface ProtocolVersion {
  major: number
  minor: number
}

// ProviderInfo
export interface ProviderInfo {
  apiBaseUrl: string
  builtin: boolean
  credential: CredentialState
  name: string
  protocol: string
  supportsImages: boolean
}

// QuestionOption
export interface QuestionOption {
  description?: string | null
  id: string
  label: string
}

// QueueEntry
export interface QueueEntry {
  attachments: Array<AssetId>
  id: QueueId
  originConversationId: ConversationId
  queuedAt: number
  steerEligible: boolean
  text: string
}

// QueueId
export type QueueId = string

// QueueReadParams
export interface QueueReadParams {
  conversationId: ConversationId
  cursor?: string | null
  limit?: number | null
}

// QueueReadResult
export interface QueueReadResult {
  count: number
  entries: Page_for_QueueEntry
}

// QueueReclaimTailParams
export interface QueueReclaimTailParams {
  conversationId: ConversationId
  expectedRevision?: number | null
}

// QueueReclaimTailResult
export interface QueueReclaimTailResult {
  outcome: ReclaimOutcome
}

// QueueRemovalReason
export type QueueRemovalReason = "drained" | "reclaimed" | "cleared"

// ReclaimOutcome
export type ReclaimOutcome = { entry: QueueEntry; revision: number; type: "reclaimed" } | { queueId: QueueId; type: "alreadyAbsorbed" } | { type: "empty" }

// RequestId
export type RequestId = number | string | null

// ResourceKind
export type ResourceKind = "agents" | "rooms" | "tasks" | "deliveries" | "backgroundCommands"

// ResourcePage
export type ResourcePage = { items: Array<AgentResource>; nextCursor?: string | null; resource: "agents"; revision: number } | { items: Array<RoomResource>; nextCursor?: string | null; resource: "rooms"; revision: number } | { items: Array<TaskResource>; nextCursor?: string | null; resource: "tasks"; revision: number } | { items: Array<DeliveryResource>; nextCursor?: string | null; resource: "deliveries"; revision: number } | { items: Array<BackgroundCommandResource>; nextCursor?: string | null; resource: "backgroundCommands"; revision: number }

// ResourceReadParams
export interface ResourceReadParams {
  cursor?: string | null
  limit?: number | null
  resource: ResourceKind
}

// ResourceReadResult
export interface ResourceReadResult {
  resource: ResourcePage
}

// ResourceRevision
export interface ResourceRevision {
  revision: number
  scope: RevisionScope
}

// RespondStatus
export type RespondStatus = "accepted"

// ResponseResult
export type ResponseResult = InitializeResult | ShutdownResult | SessionListResult | SessionStartResult | SessionResumeResult | SessionReadResult | SessionCloseResult | SessionDeleteResult | ConversationListResult | ConversationReadResult | ConversationMarkReadResult | ConversationSubmitResult | TurnInterruptResult | QueueReadResult | QueueReclaimTailResult | InteractionRespondResult | ActionListResult | ActionExecuteResult | ConfigReadResult | CatalogReadResult | ResourceReadResult | AssetRegisterPathResult | AssetReadChunkResult

// RevisionScope
export type RevisionScope = "session" | "conversation" | "queue" | "config" | "catalog" | "agents" | "rooms" | "tasks" | "team"

// RewindMode
export type RewindMode = "preview" | "applied"

// RewindTarget
export type RewindTarget = { itemId: ItemId; type: "item" } | { type: "latest" }

// RoomId
export type RoomId = string

// RoomMode
export type RoomMode = "broadcast" | "relay"

// RoomResource
export interface RoomResource {
  conversationId?: ConversationId | null
  id: RoomId
  lastSeq: number
  members: Array<string>
  mentions: number
  messageCount: number
  mode: RoomMode
  name: string
  topic?: string | null
  unread: number
  userIsMember: boolean
}

// RpcError
export interface RpcError {
  code: number
  data?: ErrorData | null
  message: string
}

// RuntimeCollections
export interface RuntimeCollections {
  agents: Collection_for_AgentResource
  backgroundCommands: Collection_for_BackgroundCommandResource
  deliveries: Collection_for_DeliveryResource
  mcpServers: Array<McpServerState>
  rooms: Collection_for_RoomResource
  tasks: Collection_for_TaskResource
}

// ScopeId
export type ScopeId = string

// ServerCapabilities
export interface ServerCapabilities {
  images: boolean
  multiConversation: boolean
  reasoning: boolean
  rooms: boolean
  shell: boolean
  teams: boolean
}

// ServerInfo
export interface ServerInfo {
  epoch: EpochId
  name: string
  version: string
}

// SessionCloseParams
export type SessionCloseParams = Record<string, unknown>

// SessionCloseReason
export type SessionCloseReason = "requested" | "disconnected" | "replaced"

// SessionCloseResult
export interface SessionCloseResult {
  sessionId: SessionId
}

// SessionDeleteParams
export interface SessionDeleteParams {
  locator: SessionLocator
}

// SessionDeleteResult
export interface SessionDeleteResult {
  deleted: boolean
  locator: SessionLocator
}

// SessionId
export type SessionId = string

// SessionListEntry
export interface SessionListEntry {
  cwd: string
  locator: SessionLocator
  messageCount: number
  open: boolean
  title: string
  updatedAt: number
}

// SessionListParams
export interface SessionListParams {
  cursor?: string | null
  limit?: number | null
}

// SessionListResult
export interface SessionListResult {
  sessions: Page_for_SessionListEntry
}

// SessionLocator
export type SessionLocator = { type: "latest" } | { stem: string; type: "stem" } | { path: string; type: "path" }

// SessionReadParams
export type SessionReadParams = Record<string, unknown>

// SessionReadResult
export interface SessionReadResult {
  snapshot: SessionSnapshot
}

// SessionResumeParams
export interface SessionResumeParams {
  locator: SessionLocator
}

// SessionResumeResult
export interface SessionResumeResult {
  snapshot: SessionSnapshot
}

// SessionScope
export interface SessionScope {
  id: ScopeId
  label: string
}

// SessionSnapshot
export interface SessionSnapshot {
  activeTurns: Array<Turn>
  capabilities: ServerCapabilities
  collections: RuntimeCollections
  config: ConfigSnapshot
  conversations: Collection_for_ConversationSummary
  eventCursor: number
  feedback: Array<Feedback>
  interactions: Array<Interaction>
  operations: Array<Operation>
  session: SessionSummary
}

// SessionStartParams
export interface SessionStartParams {
  cwd?: string | null
  model?: string | null
  permissionMode?: PermissionMode | null
  provider?: string | null
  thinking?: ThinkingLevel | null
}

// SessionStartResult
export interface SessionStartResult {
  snapshot: SessionSnapshot
}

// SessionState
export type SessionState = "active" | "closed"

// SessionSummary
export interface SessionSummary {
  createdAt: number
  cwd: string
  epoch: EpochId
  id: SessionId
  locator: SessionLocator
  model: string
  permissionMode: PermissionMode
  provider: string
  resumed: boolean
  state: SessionState
  thinking: ThinkingLevel
  title: string
  updatedAt: number
}

// ShellDialect
export type ShellDialect = "posix" | "powershell" | "cmd" | "unknown"

// ShutdownParams
export type ShutdownParams = Record<string, unknown>

// ShutdownResult
export interface ShutdownResult {
  deniedInteractions: number
  interruptedTurns: number
}

// SkillInfo
export interface SkillInfo {
  description: string
  name: string
  source: SkillSource
}

// SkillSource
export type SkillSource = "bundled" | "user" | "project" | "plugin"

// Submission
export type Submission = { attachments: Array<AssetId>; mode: ComposerMode; text: string; type: "composer" } | { attachments: Array<AssetId>; text: string; type: "sendProse" }

// SubmitDisposition
export type SubmitDisposition = { turnId: TurnId; type: "turnStarted" } | { position: number; queueId: QueueId; steerEligible: boolean; type: "queued" } | { messageId: ItemId; type: "delivered" } | { result: ActionResult; type: "applied" } | { operationId: OperationId; type: "operationStarted" }

// SuggestedAction
export type SuggestedAction = "retry" | "reinitialize" | "refreshSession" | "refreshConversation" | "refreshQueue" | "refreshActions" | "reauthenticate" | "resubmit"

// TaskId
export type TaskId = string

// TaskResource
export interface TaskResource {
  activeForm?: string | null
  blockedBy: Array<TaskId>
  blocks: Array<TaskId>
  description: string
  id: TaskId
  owner?: string | null
  status: TaskStatus
  subject: string
}

// TaskStatus
export type TaskStatus = "pending" | "inProgress" | "completed" | "cancelled"

// ThemeChoice
export type ThemeChoice = "auto" | "dark" | "light"

// ThinkingLevel
export type ThinkingLevel = "off" | "low" | "medium" | "high" | "xhigh" | "max"

// ToolRequest
export interface ToolRequest {
  input: unknown
  name: string
}

// Turn
export interface Turn {
  completedAt?: number | null
  conversationId: ConversationId
  error?: TurnError | null
  id: TurnId
  inputItemIds: Array<ItemId>
  origin: TurnOrigin
  round: number
  startedAt: number
  status: TurnStatus
  usage?: TurnUsage | null
}

// TurnError
export interface TurnError {
  code: string
  message: string
}

// TurnId
export type TurnId = string

// TurnInterruptParams
export interface TurnInterruptParams {
  conversationId: ConversationId
  turnId: TurnId
}

// TurnInterruptResult
export interface TurnInterruptResult {
  accepted: boolean
  turnId: TurnId
}

// TurnOrigin
export type TurnOrigin = "user" | "queue" | "peer" | "auto" | "shell"

// TurnStatus
export type TurnStatus = "running" | "completed" | "failed" | "cancelled" | "interrupted"

// TurnUsage
export interface TurnUsage {
  authoritative: boolean
  cacheReadTokens: number
  cacheWriteTokens: number
  inputTokens: number
  outputTokens: number
}

export type AppServerRequest =
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "initialize"; params: InitializeParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "shutdown"; params: ShutdownParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "session/list"; params: SessionListParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "session/start"; params: SessionStartParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "session/resume"; params: SessionResumeParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "session/read"; params: SessionReadParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "session/close"; params: SessionCloseParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "session/delete"; params: SessionDeleteParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "conversation/list"; params: ConversationListParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "conversation/read"; params: ConversationReadParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "conversation/markRead"; params: ConversationMarkReadParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "conversation/submit"; params: ConversationSubmitParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "turn/interrupt"; params: TurnInterruptParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "queue/read"; params: QueueReadParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "queue/reclaimTail"; params: QueueReclaimTailParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "interaction/respond"; params: InteractionRespondParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "action/list"; params: ActionListParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "action/execute"; params: ActionExecuteParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "config/read"; params: ConfigReadParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "catalog/read"; params: CatalogReadParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "resource/read"; params: ResourceReadParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "asset/registerPath"; params: AssetRegisterPathParams }
  | { id: RequestId; jsonrpc: JsonRpcVersion; method: "asset/readChunk"; params: AssetReadChunkParams }

export type AppServerNotification =
  | { jsonrpc: JsonRpcVersion; method: "session/updated"; params: NotificationParams_for_SessionUpdated }
  | { jsonrpc: JsonRpcVersion; method: "session/closed"; params: NotificationParams_for_SessionClosed }
  | { jsonrpc: JsonRpcVersion; method: "session/deleted"; params: NotificationParams_for_SessionDeleted }
  | { jsonrpc: JsonRpcVersion; method: "conversation/created"; params: NotificationParams_for_ConversationChanged }
  | { jsonrpc: JsonRpcVersion; method: "conversation/updated"; params: NotificationParams_for_ConversationChanged }
  | { jsonrpc: JsonRpcVersion; method: "conversation/removed"; params: NotificationParams_for_ConversationRemoved }
  | { jsonrpc: JsonRpcVersion; method: "turn/started"; params: NotificationParams_for_TurnChanged }
  | { jsonrpc: JsonRpcVersion; method: "turn/roundStarted"; params: NotificationParams_for_TurnRoundStarted }
  | { jsonrpc: JsonRpcVersion; method: "turn/retrying"; params: NotificationParams_for_TurnRetrying }
  | { jsonrpc: JsonRpcVersion; method: "turn/roundCompleted"; params: NotificationParams_for_TurnRoundCompleted }
  | { jsonrpc: JsonRpcVersion; method: "turn/usageUpdated"; params: NotificationParams_for_TurnUsageUpdated }
  | { jsonrpc: JsonRpcVersion; method: "turn/completed"; params: NotificationParams_for_TurnChanged }
  | { jsonrpc: JsonRpcVersion; method: "item/started"; params: NotificationParams_for_ItemChanged }
  | { jsonrpc: JsonRpcVersion; method: "item/textDelta"; params: NotificationParams_for_ItemDelta }
  | { jsonrpc: JsonRpcVersion; method: "item/reasoningDelta"; params: NotificationParams_for_ItemDelta }
  | { jsonrpc: JsonRpcVersion; method: "item/commandTailUpdated"; params: NotificationParams_for_ItemCommandTailUpdated }
  | { jsonrpc: JsonRpcVersion; method: "item/updated"; params: NotificationParams_for_ItemChanged }
  | { jsonrpc: JsonRpcVersion; method: "item/completed"; params: NotificationParams_for_ItemChanged }
  | { jsonrpc: JsonRpcVersion; method: "queue/itemAdded"; params: NotificationParams_for_QueueItemAdded }
  | { jsonrpc: JsonRpcVersion; method: "queue/itemRemoved"; params: NotificationParams_for_QueueItemRemoved }
  | { jsonrpc: JsonRpcVersion; method: "queue/itemAbsorbed"; params: NotificationParams_for_QueueItemAbsorbed }
  | { jsonrpc: JsonRpcVersion; method: "interaction/opened"; params: NotificationParams_for_InteractionOpened }
  | { jsonrpc: JsonRpcVersion; method: "interaction/resolved"; params: NotificationParams_for_InteractionResolved }
  | { jsonrpc: JsonRpcVersion; method: "interaction/cancelled"; params: NotificationParams_for_InteractionCancelled }
  | { jsonrpc: JsonRpcVersion; method: "agent/changed"; params: NotificationParams_for_AgentChanged }
  | { jsonrpc: JsonRpcVersion; method: "agent/removed"; params: NotificationParams_for_AgentRemoved }
  | { jsonrpc: JsonRpcVersion; method: "room/changed"; params: NotificationParams_for_RoomChanged }
  | { jsonrpc: JsonRpcVersion; method: "task/changed"; params: NotificationParams_for_TaskChanged }
  | { jsonrpc: JsonRpcVersion; method: "task/removed"; params: NotificationParams_for_TaskRemoved }
  | { jsonrpc: JsonRpcVersion; method: "delivery/changed"; params: NotificationParams_for_DeliveryChanged }
  | { jsonrpc: JsonRpcVersion; method: "command/changed"; params: NotificationParams_for_CommandChanged }
  | { jsonrpc: JsonRpcVersion; method: "operation/started"; params: NotificationParams_for_OperationChanged }
  | { jsonrpc: JsonRpcVersion; method: "operation/progress"; params: NotificationParams_for_OperationProgressed }
  | { jsonrpc: JsonRpcVersion; method: "operation/completed"; params: NotificationParams_for_OperationChanged }
  | { jsonrpc: JsonRpcVersion; method: "config/changed"; params: NotificationParams_for_ConfigChanged }
  | { jsonrpc: JsonRpcVersion; method: "catalog/changed"; params: NotificationParams_for_CatalogChanged }
  | { jsonrpc: JsonRpcVersion; method: "asset/available"; params: NotificationParams_for_AssetAvailable }
  | { jsonrpc: JsonRpcVersion; method: "feedback/raised"; params: NotificationParams_for_FeedbackRaised }
  | { jsonrpc: JsonRpcVersion; method: "feedback/cleared"; params: NotificationParams_for_FeedbackCleared }

export type AppServerClientNotification =
  | { jsonrpc: JsonRpcVersion; method: "initialized"; params: InitializedParams }

export type AppServerResponse = { error?: RpcError | null; id: RequestId; jsonrpc: JsonRpcVersion; result?: ResponseResult | null }

export type AppServerRpcError = { code: number; data?: ErrorData | null; message: string }

